### ISSUE TITLE
Provide the clean up at the tests end

### ISSUE THREAD

**Issue by polina-popova** [tolstoyevsky/rocketchat-tests-based-on-splinter#53]
Write a method which will finalize the tests scenario (even interrupted by user) and delete all artifacts created by the tests (users, channels and so on).

**Comment by BehindLoader** [comment]
**Tasks**

@BehindLoader
- [ ] Fix `check_with_retries` method

@ABSLord
- [ ] Add method `delete_all_extra_channels`

pool
- [ ] Expanse `setup` and `tear_down` method
